### ISSUE TITLE
"cannot unpack non-iterable NoneType object."

### ISSUE THREAD

**Issue by blairdrummond** [IBM/jupyterlab-s3-browser#15]
Seems idiosyncratic, but on some folders, I get this error

![sreenshot-2020-04-23_23-04-1587698705](https://user-images.githubusercontent.com/10801138/80171952-b75d2400-85b9-11ea-8652-9f34d6b719f7.png)

However the folder is not empty, I can see the contents in minio. I don't have any fancy policies, though I don't know this tech well. Error on the notebook server is below

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/jupyterlab_s3_browser/__init__.py", line 230, in do_get_object
    response = s3client.get_object(Bucket=bucket_name, Key=path)
  File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[I 03:22:16.904 NotebookApp] Build is up to date
```

As I said, the folders definitely exist

**Comment by blairdrummond** [comment]
It seems to not play nice with folders within buckets in general? Does it expect a flat file layout?

**Comment by reevejd** [comment]
Thanks for opening the issue. It's supposed to work for any file layout. I'll take a look later today.

**Comment by reevejd** [comment]
I'm able to reproduce the issue. Unless I'm mistaken it's minio specific, which is surprising. I fully intend for this extension to support minio so I'll continue looking into it. Thanks again for raising the issue.

**Comment by blairdrummond** [comment]
Yeah I did run this on minio; I should have mentioned that!

**Comment by t14g0p** [comment]
Hey, I'm also having the same issue. Not using minio.

**Comment by reevejd** [comment]
Thanks for the info. I believe this has now been fixed in the most recent releases for JupyterLab 1.x and 2.x. Please reopen this issue if you continue to encounter it after updating. Thanks!

**Comment by jarutis** [comment]
Still seeing this Amazon S3 and

jupyterlab==2.2.2
jupyterlab-s3-browser==0.6.1

I can provide more info if there is something that would help.

**Comment by reevejd** [comment]
@jarutis what version of the labextension are you using? You can run `jupyter labextension list` to show the versions of all the labextensions you have installed.

**Comment by reevejd** [comment]
Sorry for the delayed response. if you update from version `0.4.1` to `0.6.1` it should resolve the issue. If not, please let me know.
